from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome()
driver.get("http://127.0.0.1:5000/")


def test_input(chatbox_input: str):
    input_box = driver.find_element(By.ID, "userInput")
    input_box.send_keys(chatbox_input)
    input_box.send_keys(Keys.RETURN)

    response = driver.find_element(By.ID, "chatlog")
    time.sleep(1)
    print(f"Chatbot response: {response.text}\n")


test_input("I really enjoy playing games")
test_input("The cat jumped over the fence")
test_input("She reads a new book every week")
test_input("Rainy days make me feel cozy")
test_input("He forgot to lock the door")
test_input("We traveled across the country")
test_input("The pizza was absolutely delicious")
test_input("My phone battery dies quickly")
test_input("I can hear the birds singing")
test_input("They danced all night long")
test_input("I’m learning to play the guitar")
test_input("Sunsets at the beach are amazing")
test_input("The movie had a surprising twist")
test_input("Dogs are loyal and friendly animals")
test_input("She wore a beautiful red dress")
test_input("I lost my keys again")
test_input("We watched the stars together")
test_input("He runs five miles every morning")
test_input("The cake was too sweet for me")
test_input("I’m planning a trip to Japan")
test_input("The wind howled through the trees")
test_input("He studies astronomy at university")
test_input("I enjoy working from home")
test_input("The garden is full of flowers")
test_input("They adopted a puppy yesterday")
test_input("This song reminds me of summer")
test_input("She paints portraits in her free time")
test_input("The lake was calm and clear")
test_input("I met my best friend in high school")
test_input("The train was delayed by an hour")
test_input("I’m making pasta for dinner")
test_input("He always forgets his wallet")
test_input("The smell of fresh coffee wakes me up")
test_input("We hiked up the mountain trail")
test_input("I miss the smell of the ocean")
test_input("She sings in a local band")
test_input("The kids built a treehouse")
test_input("My laptop is running slow")
test_input("We need to buy more milk")
test_input("He plays the drums in a jazz group")
test_input("They planted tomatoes in the backyard")
test_input("I binge-watched a whole season")
test_input("The air felt crisp and cold")
test_input("She knits scarves for winter")
test_input("I forgot to set my alarm")
test_input("They watched a thunderstorm roll in")
test_input("The baby giggled at the toy")
test_input("I’m learning to speak French")
test_input("We spent the day at the museum")
test_input("He’s building a robot from scratch")
test_input("I made pancakes for breakfast")
test_input("The fire crackled in the fireplace")
test_input("She runs a popular blog")
test_input("My shoes are soaking wet")
test_input("We saw dolphins at the beach")
test_input("He collects vintage stamps")
test_input("I’ve never seen snow before")
test_input("The moonlight lit up the path")
test_input("She takes beautiful photographs")
test_input("I’m baking cookies for the party")
test_input("We’re redecorating the living room")
test_input("The stars were bright last night")
test_input("He works in a tech startup")
test_input("My favorite color is green")
test_input("She grew up on a farm")
test_input("I spilled coffee on my shirt")
test_input("They went skydiving last weekend")
test_input("He just bought a new bicycle")
test_input("We built a sandcastle together")
test_input("I love the smell of rain")
test_input("She practices yoga every morning")
test_input("The kids are watching cartoons")
test_input("I got lost in the bookstore")
test_input("He’s learning how to code")
test_input("We saw a shooting star")
test_input("She likes spicy food")
test_input("My car won’t start")
test_input("They made a snowman in the yard")
test_input("I wrote a poem about autumn")
test_input("He enjoys solving puzzles")
test_input("We’re going camping next week")
test_input("She found a shell on the beach")
test_input("I’m organizing my closet")
test_input("He likes to draw comic books")
test_input("We danced in the rain")
test_input("I’m watching a documentary tonight")
test_input("They built a raft from wood")
test_input("She wore a funny hat")
test_input("I watered the plants this morning")
test_input("He fixed the leaky faucet")
test_input("We toasted marshmallows by the fire")
test_input("She collects seashells")
test_input("I mailed the package yesterday")
test_input("They flew a kite in the park")
test_input("He painted the wall blue")
test_input("We made lemonade from scratch")
test_input("She bought a vintage camera")
test_input("I’m listening to jazz right now")
test_input("He taught me how to juggle")
test_input("We made homemade ice cream")






driver.quit()
